AWSTemplateFormatVersion: "2010-09-09"
Description: Style Thief Infrastructure
Resources:

  # VPC
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/24
      Tags:
        - Key: name
          Value: VPC

  # Internet Gateway
  IGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: name
          Value: IGW

  # Gateway Attachment
  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref IGW
      VpcId: !Ref VPC

  # Public Subnet
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.0.0/25
      AvailabilityZone: us-east-1a
      VpcId: !Ref VPC
      Tags:
        - Key: name
          Value: Public-subnet

  # Public Subnet Route Table
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: name
          Value: Public-route-table

  # Public Route Table Association
  PublicRouteAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet
  
  # IGW Route
  IGWRoute:
    Type: AWS::EC2::Route
    DependsOn: VPCGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IGW

  # Instance Profile for ec2
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    DependsOn: IamRole
    Properties:
      Roles:
        - StyleThiefRole

  # IAM Role for s3 access
  IamRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: StyleThiefRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
              Action:
                - sts:AssumeRole

  # EC2 Instance for Style Thief API
  EC2Instance:
    Type: AWS::EC2::Instance
    DependsOn: InstanceProfile
    Properties: 
      ImageId: 
      AvailabilityZone:
      InstanceType:
      IamInstanceProfile:
      KeyName: style-thief
      SubnetId: !Ref PublicSubnet
      UserData:
        !Base64 |
          #!/bin/bash
          yum update -y
          
  
  
